### ISSUE TITLE
Remove full URL from `*_metadata_tarball.json`

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/inm-icf-utilities#23]
I think having the URL in the tarball presents an encapsulation issue. If the store ever moves (as a whole), the metadata would become invalid and needs an update. I propose to turn

```json
{
  "size": 792207360,
  "md5": "985e680a221e47db05063a12b91d7d89",
  "path": "icf/P000624_dicom.tar",
  "url": "https://data.inm-icf.de/dl-Z03/P000624_dicom.tar"
}
```

into something lilke

```json
{
  "size": 792207360,
  "md5": "985e680a221e47db05063a12b91d7d89",
  "dspath": "icf/P000624_dicom.tar",
  "storepath": "dl-Z03/P000624_dicom.tar"
}
```

The full URL can be generated by completing it with the base URL of the day when generating a catalog or a dataset.

Ping @jsheunis

**Comment by jsheunis** [comment]
makes sense to me. I'll do a quick PR.
