### ISSUE TITLE
ICF catalog logo cut out

### ISSUE THREAD

**Issue by mslw** [psychoinformatics-de/inm-icf-utilities#51]
The page (viewbox) size of `assets/fzj_icf_logo.svg` SVG file (used to display the logo on top of a generated catalog) seems to be too small to fit the text. This is what it looks like in Inkscape for me:

![Screenshot from 2024-06-21 09-32-15](https://github.com/psychoinformatics-de/inm-icf-utilities/assets/11985212/34723926-19ee-402e-92dc-16102bb542a2)

And this is also what it looks like in the generated catalog for me (cut off at ICF Study Ca).

Note that this can also be caused by the font - it is set to Apple Symbols, which I do not have (and it is unlikely to be available by default on non-apple OSs), so what is shown is the closest replacement chosen by the system. Looking at the SVG XML, I see that the text element specifies Nanum Pen, but the tspan element specifies Apple Symbols. Nanum Pen at a given size fits into the page.

In any case, given that the catalog page is meant to be viewed on user computers, I would convert the text to paths, or even convert the logo to png. A suitable font could be Weissenhof Grotesk (Jülich’s corporate font, according to our Corporate Design Handbook), but it is proprietary. I would go for something more neutral then Naunum Pen (maybe even Liberation Sans or Free Sans).

**Comment by christian-monch** [comment]
I think it is a good idea to convert them to paths. How about the font "Hanken Grotesk", the lower case "y" is different and the capital "C" is not as slim as in "Weissenhof Grotesk" though.

![image](https://github.com/psychoinformatics-de/inm-icf-utilities/assets/17925232/08afeb3f-505b-4ab8-8e3b-ef181ef7fe83)
